import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HamButton from "./components/hambutton";

import AuthProvider from "./api/auth/provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <nav className="h-[4rem] bg-[#EEE2DC] flex items-center justify-center fixed top-0 w-full z-10">
            <div className="top-[1.25rem] font-black text-3xl text-[#AC3B61]">JAM</div>
          </nav>
          {children}

        </body>
      </AuthProvider>
    </html>
  );
}
