import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HamButton from "./components/hambutton";

import AuthProvider from "./api/auth/provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <nav className="h-[4rem] bg-slate-400 fixed top-0 w-full z-10">
          <div className="container mx-auto">
            <nav className="flex items-center justify-end">
            <a href="/login" className="absolute top-[.1rem] right-[1.5rem] bg-inherit rounded-md flex items-center justify-center underline underline-offset-1 mt-[1.25rem] text-white">Login</a>
            </nav>
          </div>  
          </nav>
          {children}

        </body>
      </AuthProvider>
    </html>
  );
}
